[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
tokio = { version = "1.53.1", features = ["full"] }
db_wrapper = { git = "https://github.com/Zakarias-Viinikka/z_db", default-features = false, features = ["native"] }
protocol = { git = "https://github.com/Zakarias-Viinikka/z_db" }
server_protocol = { path = "../server_protocol" }
server_db_schema = { path = "../server_db_schema" }
