pub mod errorEnumThatWorksWithQuestion;
pub mod implementErrAndDisplayOnCustomEnum;
pub mod multiPurposeMethod;
pub mod structThatHoldsReferenceThatIsT;
pub mod structWithGenericT_AndDefaultDoSomethingMethod;
pub mod traitThatExistsToCheckConditions;
